import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local'
import "./globals.css";
import NavBar from "./components/NavBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const macondoSwashCaps = localFont({
  src:'fonts/MacondoSwashCaps-Regular.ttf',
  variable:'--font-macondo-swash-caps',
})

export const metadata: Metadata = {
  title: "Medieval Companion",
  description: "Generated by Shadow Productions",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="coffee">
      <body
        className={`${macondoSwashCaps.className} `}
      >
        <NavBar/>
        <main className="flex-1 flex flex-col min-h-screen">{children}</main>

      </body>
    </html>
  );
}
